name: CI
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          sleep 9
  build_2:
   runs-on: ubuntu-latest
   needs: [build]
   steps:
      - uses: actions/checkout@v3
      - name: Run a two-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          sleep 9
  test:
    needs: [build, build_2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running testing script
        run: |
          echo TESTING...
          sleep 6
  publish:
    needs: [build, build_2, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running testing script
        run: | 
          echo PUBLISHING...
          sleep 6

