name: OctaneIntegration

on:
  workflow_run:
    workflows: [CI]
    types: [requested, completed]

run-name: OctaneIntegration#${{github.event.action}}

jobs:
  octane_integration_job:
    runs-on: [self-hosted, java]
    name: Octane Integration
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - run:  npm config set strict-ssl false
      - name: Checkout
        uses: actions/checkout@v3
      - name: GitHub Actions ALM Octane Integration
        uses: ./ # Uses an action in the root directory
        id: gitHubActionsIntegration
        with:
          octaneUrl: 'https://sec-pen-test.octane.admlabs.aws.swinfra.net:8443'
          octaneSharedSpace: 1001
          octaneWorkspace: 1002
          octaneClientId: ${{secrets.ALM_OCTANE_CLIENT_ID}}
          octaneClientSecret: ${{secrets.ALM_OCTANE_CLIENT_SECRET}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
          serverBaseUrl: https://github.com/madaC/Actions
